site_name: Opal Issan #name of your site.
site_description: In this website, I will discuss my academic background and research experience which led me to discover my curiosity in mathematical modeling, numerical optimization, dynamical systems, and machine learning.

theme:
  name: material
  language: en
  palette:
    primary: black
    accent: indigo

nav:
  - Home: index.md

markdown_extensions:
  - codehilite:
      linenums: true
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.mark
  - pymdownx.tabbed
  - pymdownx.arithmatex


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

plugins:
  - search:
      lang: en
